name: BOOK

on:
  push:

jobs:
    marimo:
      runs-on: "ubuntu-latest"

      steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        - uses: ./actions/environment

        - uses: ./actions/marimo

    pdoc:
      runs-on: "ubuntu-latest"
      steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        - uses: ./actions/environment

        - uses: ./actions/pdoc

    sphinx:
      runs-on: "ubuntu-latest"
      steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        - uses: ./actions/environment

        - uses: ./actions/sphinx
          with:
            sphinx-folder: 'book/sphinx'

    test:
      runs-on: "ubuntu-latest"
      steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        - uses: ./actions/environment

        - uses: ./actions/coverage
          with:
            coveralls: 'false'
            tests-folder: 'src/tests'

    jupyter:
      runs-on: "ubuntu-latest"
      steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        - uses: ./actions/environment

        - uses: ./actions/jupyter

    book:
      runs-on: "ubuntu-latest"
      needs: [test, pdoc, sphinx, jupyter, marimo]

      permissions:
        contents: write

      steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        - uses: ./actions/book
