name: BOOK

on:
  push:

jobs:
    marimo:
      runs-on: "ubuntu-latest"

      steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        - uses: ./actions/environment/uv
          with:
            working-directory: '.github/hello-world'

        - uses: ./actions/marimo
          with:
            working-directory: .github/hello-world

    pdoc:
      runs-on: "ubuntu-latest"
      steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        - uses: ./actions/environment/uv
          with:
            working-directory: '.github/hello-world'

        - uses: ./actions/pdoc
          with:
            working-directory: .github/hello-world

    sphinx:
      runs-on: "ubuntu-latest"
      steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        - uses: ./actions/environment/uv
          with:
            working-directory: '.github/hello-world'

        - uses: ./actions/sphinx
          with:
            working-directory: .github/hello-world

    test:
      runs-on: "ubuntu-latest"
      steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        - uses: ./actions/environment/uv
          with:
            working-directory: '.github/hello-world'

        - uses: ./actions/coverage
          with:
            working-directory: .github/hello-world
            coveralls: 'false'

    jupyter:
      runs-on: "ubuntu-latest"
      steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        - uses: ./actions/jupyter
          with:
            working-directory: .github/hello-world

    book:
      runs-on: "ubuntu-latest"
      needs: [test, pdoc, sphinx, jupyter, marimo]

      permissions:
        contents: write

      steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        - uses: ./actions/book
