name: CI

on:
  push:

jobs:

  pass:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4


      - name: Setup an environment
        uses: ./actions/uv/setup
        with:
          working-directory: .github/hello-world

      - name: Test a project
        uses: ./actions/uv/test
        with:
          working-directory: .github/hello-world
