name: CI

on:
  push:

jobs:

  pass:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [ '3.10', '3.11', '3.12', '3.13']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: ./actions/environment/uv
        with:
          working-directory: '.github/hello-world'
          python-version:  ${{ matrix.python-version }}

      - name: Test a project
        uses: ./actions/test
        with:
          working-directory: .github/hello-world
